### ISSUE TITLE
Blowpipe is also benefiting from ammo slot

### ISSUE THREAD

**Issue by SuperNerdEric** [weirdgloop/osrs-dps-calc#107]
### What went wrong?

If you have a blowpipe equipped and also have ammo in your ammo slot it increases your max hit much higher than it should. This is an easy trap to fall into especially because the range equipment presets have Dragon arrows on them.

https://dps.osrs.wiki/?id=e942ce5f-759d-4113-81ba-8de8fcbe7039
![image](https://github.com/weirdgloop/osrs-dps-calc/assets/7608429/7d8b4a13-8ddb-414d-abb6-4044da7b34ad)

### What browsers are you seeing the problem on?

Firefox

### What device(s) are you seeing the problem on?

Windows

**Comment by LlemonDuck** [comment]
This is going to need a fairly large ammo-applicability system to support all the different types of ranged weapons and their ammunitions.

I think for now as a bandaid we can at least remove dragon arrows from the max ranged preset.

**Comment by jayktaylor** [comment]
I think let's not worry about changing the preset right now. AFAIK, it matches the DPS calc sheet people use.

It's probably worth taking the time making sure that specific ammo can only be equipped with specific weapon combinations. This is probably something I can work on at the UI level rather than in the calc code.
