### ISSUE TITLE
Equipping a bow without appropriate ammo should result in "---" DPS

### ISSUE THREAD

**Issue by jayktaylor** [weirdgloop/osrs-dps-calc#120]
### What went wrong?

<img width="1476" alt="Screenshot 2024-01-20 at 01 29 23" src="https://github.com/weirdgloop/osrs-dps-calc/assets/7265189/d4827f22-50a6-43e0-b075-66a774ac1a80">

### What did you expect to happen?

In this scenario, max hit, DPS, and TTK should show `---`. Hit distribution should also only show 0. The player can't physically attack a monster at all if not using appropriate ammo.

This function can be used to determine whether the ammo is valid: https://github.com/weirdgloop/osrs-dps-calc/blob/main/src/lib/Equipment.ts#L113

### What browsers are you seeing the problem on?

Firefox

### What device(s) are you seeing the problem on?

Windows

**Comment by LlemonDuck** [comment]
@jayktaylor You should check these two changes for your future use:
* [I rewrote `isValidAmmoForRangedWeapon`](https://github.com/weirdgloop/osrs-dps-calc/commit/a06fef1f7894eda9ad7d9cdf1a0bbdd7b915609c?diff=split&w=0#diff-93df679d519f567a6b2e660c6dab5ad7645773fe291cf7e7bb72504017b586abR115-R144) to support this in order to expose a tri-state of either the ammo is totally invalid, fine but not used, or actually used by the weapon. 
* [I changed `calculateEquipmentBonusesFromGear`](https://github.com/weirdgloop/osrs-dps-calc/commit/a06fef1f7894eda9ad7d9cdf1a0bbdd7b915609c?diff=split&w=0#diff-93df679d519f567a6b2e660c6dab5ad7645773fe291cf7e7bb72504017b586abR398-R410) to only filter out the `offensive.ranged` and `bonuses.ranged_str` stats on inapplicable ammo. This is required to support things like Rada's blessing providing a prayer bonus from the ammo slot despite not being used.
