### ISSUE TITLE
Elite void not applying accuracy bonuses

### ISSUE THREAD

**Issue by jmyaeger** [weirdgloop/osrs-dps-calc#60]
### What went wrong?

Equipping full elite void does not produce the expected accuracy boost for any combat style. 

### What did you expect to happen?

Elite void should provide the same accuracy boost as normal void, but it does not (though normal void does provide the correct boost). 

### What browsers are you seeing the problem on?

Safari

### What device(s) are you seeing the problem on?

iOS

### Any other information

Looks like the accuracy roll code is only checking if the player is wearing full normal void. The damage boost from elite void is working correctly.

**Comment by SuperNerdEric** [comment]
Somewhat related: If you wear a mix of elite and normal void like: 
`['Void ranger helm', 'Elite void top', 'Void knight robe', 'Void knight gloves']`
It doesn't recognize that you a full normal set equipped.

Kind of an edge case because most normal people would only chose the full elite or full normal set.

**Comment by LlemonDuck** [comment]
carrying over your mixed loadout comment to #63
