### ISSUE TITLE
Player gear is not stored in browser session

### ISSUE THREAD

**Issue by LlemonDuck** [weirdgloop/osrs-dps-calc#7]
Each time I reload the page my equipment is lost, although the player name is preserved and re-looked-up. We should store the other loadout information to the browser session so it persists across reloads.

**Comment by jayktaylor** [comment]
I can see people trying out different equipment sets in the calculator often enough that it would probably be annoying to persist their last equipment set in the calculator. It makes sense for us to currently persist their username so that we can lookup their stats, as that's something that users of the calculator are unlikely to go in and change, compared to equipment which will probably be changed frequently by the user.

If there is enough demand for this, then perhaps we can revisit it, but I see this as being far less useful than persisting the player's username at the moment. I also think that the usefulness of this would probably go down over time, especially if #32 is completed, which would likely become most people's main entry point into the calculator.
