### ISSUE TITLE
Equipment filter resizes itself too small

### ISSUE THREAD

**Issue by SuperNerdEric** [weirdgloop/osrs-dps-calc#71]
### What went wrong?

When filtering equipment the dropdown box shrinks if there's less results, which is fine. However, it seems to be shrinking too much and creating a scroll bar unnecessarily. 

In this example there's only 2 results but the one I want is cut off unless I scroll which is a little awkward.
![image](https://github.com/weirdgloop/osrs-dps-calc/assets/7608429/5a603c8e-982a-4a97-9d45-1ded120005c1)

Another example with 3 results and the Twisted buckler is totally off the bar
![image](https://github.com/weirdgloop/osrs-dps-calc/assets/7608429/53832fc5-5b95-4f30-9e91-794329051b90)

### What browsers are you seeing the problem on?

Firefox

### What device(s) are you seeing the problem on?

Windows

**Comment by jayktaylor** [comment]
Honestly, this comes from a few days spent tinkering with the [react-window](https://github.com/bvaughn/react-window) library to try and get it to work how we want. We use react-window to ensure that we're not loading a shit ton of dropdown elements at once, but it seems to be a bit funky when we try and determine what the height of the list should be. If I recall, this is because the elements in the list can span more than one line.

Admittedly, the last time I looked at this specific part of the code was probably back in 2022 now, when we were first outlining what we wanted a UI to look like (it was only me developing it at the time). There might be something very obvious that can be done to make this better that I didn't consider at the time.

I welcome PRs if anyone is able to get this to work properly!
